tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "romkatv/powerlevel10k"

# A cat(1) clone with syntax highlighting and Git integration.
# https://github.com/sharkdp/bat
brew "bat"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Mac App Store command-line interface
brew "mas"
# Dependency manager that installs and runs Swift command-line tool packages
brew "mint"
# Install various Ruby versions and implementations
brew "ruby-build"
# Changes the current Ruby.
# https://github.com/postmodern/chruby
brew "chruby"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Formatting tool for reformatting Swift code
brew "swiftformat"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Generate your Xcode project from a spec file and your folder structure
brew "xcodegen"
# UNIX shell (command interpreter)
brew "zsh"
# A Zsh Theme
brew "romkatv/powerlevel10k/powerlevel10k"

#########################################################################
# cask                                                                  #
#########################################################################

# Application launcher and productivity software
cask "alfred", args: { appdir: "/Applications" }
# GIT client
cask "fork", args: { appdir: "/Applications" }
# Web browser
cask "google-chrome", args: { appdir: "/Applications" }
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2", args: { appdir: "/Applications" }
# App to write, plan, collaborate, and get organized
cask "notion", args: { appdir: "/Applications" }
# HTTP client that helps testing and describing APIs
cask "postman", args: { appdir: "/Applications" }
# Powerful runtime view debugging for iOS developers
cask "reveal", args: { appdir: "/Applications" }
# Team communication and collaboration software
cask "slack", args: { appdir: "/Applications" }
# Xcode Extension for reformatting Swift code
cask "swiftformat-for-xcode", args: { appdir: "/Applications" }
# Open-source code editor
cask "visual-studio-code", args: { appdir: "/Applications" }
# Install and switch between multiple versions of Xcode
cask "xcodes", args: { appdir: "/Applications" }
# Share, organize and collaborate on designs
cask "zeplin", args: { appdir: "/Applications" }


# font
cask "font-inconsolata", args: { appdir: "/Applications" }
mas "DevCleaner", id: 1388020431
mas "Dynamic Wallpaper", id: 1453504509
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
mas "Translate Tab", id: 458887729
